In [2]:
import torch
import numpy

In [3]:
#Usual type of data which we use in PyTorch - is tensors (n-dimensional matrices)

In [4]:
#Create zero matrix with 3 rows and 4 columns
torch.zeros([3,4])

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [7]:
#Create 3 ones matrices with 3 rows and 3 columns
torch.ones([4,3,3])

tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])

In [12]:
#Create our own Tensor

torch.Tensor([[1,1,1],
             [2,2,2],
             [3,3,3]])

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

In [13]:
x = torch.Tensor([[1,1,1],
             [2,2,2],
             [3,3,3]])

In [14]:
print(x.size(), x.shape)

torch.Size([3, 3]) torch.Size([3, 3])


In [15]:
#First row
x[0]

tensor([1., 1., 1.])

In [17]:
#Second row
x[1]

tensor([2., 2., 2.])

In [18]:
#Take a slice for 0 column
print('Zero column', x[:, 0])

Zero column tensor([1., 2., 3.])


In [19]:
#Check it
x

tensor([[1., 1., 1.],
        [2., 2., 2.],
        [3., 3., 3.]])

Opeartions with tensor:

 - 1) Addition (x + 10) --> 10 will be added to each element
 - 2) Square (x ** 2) --> the same, all the elements will be power of 2

In [20]:
x + 10

tensor([[11., 11., 11.],
        [12., 12., 12.],
        [13., 13., 13.]])

In [21]:
x ** 2

tensor([[1., 1., 1.],
        [4., 4., 4.],
        [9., 9., 9.]])

In [22]:
a = torch.ones([5,4])
b = torch.Tensor([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16],
                  [17,18,19,20]])

In [23]:
a + b

tensor([[ 2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9.],
        [10., 11., 12., 13.],
        [14., 15., 16., 17.],
        [18., 19., 20., 21.]])

In [24]:
b[0] + a[2]

tensor([2., 3., 4., 5.])

In [25]:
a % b

tensor([[0., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
a.shape

torch.Size([5, 4])

In [33]:
#Another operations as exp(), log(), sin()
print(torch.exp(x),'\n ', torch.log(x),'\n ', torch.sin(x))

tensor([[ 2.7183,  2.7183,  2.7183],
        [ 7.3891,  7.3891,  7.3891],
        [20.0855, 20.0855, 20.0855]]) 
  tensor([[0.0000, 0.0000, 0.0000],
        [0.6931, 0.6931, 0.6931],
        [1.0986, 1.0986, 1.0986]]) 
  tensor([[0.8415, 0.8415, 0.8415],
        [0.9093, 0.9093, 0.9093],
        [0.1411, 0.1411, 0.1411]])


In [39]:
#Logical operations
b > 3

tensor([[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [40]:
#Logical operations
a > 2

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [44]:
mask = b > 3
mask

tensor([[False, False, False,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]])

In [45]:
b[mask]

tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13., 14., 15., 16., 17.,
        18., 19., 20.])

In [48]:
#Calculates the sum of matrix of elements which are larger than defined liitation from user's input

def summation():
    """Calculates the sum of matrix of elements 
    which are larger than defined liitation from user's input"""
    X = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    print(X)
    #Defined limit from user
    limit = int(input())
    larger_than_limit_sum = X[X > limit].sum()
#   print(larger_than_limit_sum)
    return larger_than_limit_sum

In [49]:
summation()

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
3


tensor(39)

In [50]:
# In order to clone independent(NOT SHALLOW LINKED) object(tensor) in our memory we need to use torch.clone
#Let us have a look

In [53]:
x = torch.Tensor([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16],
                  [17,18,19,20]])

y = x

print(x, '\n')
print(y, '\n')

y[0][0] = 1000

print(x, '\n')
print(y)

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.],
        [17., 18., 19., 20.]]) 

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.],
        [13., 14., 15., 16.],
        [17., 18., 19., 20.]]) 

tensor([[1000.,    2.,    3.,    4.],
        [   5.,    6.,    7.,    8.],
        [   9.,   10.,   11.,   12.],
        [  13.,   14.,   15.,   16.],
        [  17.,   18.,   19.,   20.]]) 

tensor([[1000.,    2.,    3.,    4.],
        [   5.,    6.,    7.,    8.],
        [   9.,   10.,   11.,   12.],
        [  13.,   14.,   15.,   16.],
        [  17.,   18.,   19.,   20.]])


In [56]:
# As we can observe the value had changed in both cases (tensors). 
#In order to avoid this, we need to use torch.clone

print(x, '\n')

z = x.clone()
z[0][0] = -1000

print(x, '\n')
print(z, '\n')

tensor([[1000.,    2.,    3.,    4.],
        [   5.,    6.,    7.,    8.],
        [   9.,   10.,   11.,   12.],
        [  13.,   14.,   15.,   16.],
        [  17.,   18.,   19.,   20.]]) 

tensor([[1000.,    2.,    3.,    4.],
        [   5.,    6.,    7.,    8.],
        [   9.,   10.,   11.,   12.],
        [  13.,   14.,   15.,   16.],
        [  17.,   18.,   19.,   20.]]) 

tensor([[-1000.,     2.,     3.,     4.],
        [    5.,     6.,     7.,     8.],
        [    9.,    10.,    11.,    12.],
        [   13.,    14.,    15.,    16.],
        [   17.,    18.,    19.,    20.]]) 



In [58]:
x = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
y = x
y[2] = torch.ones(3)

print(x, '\n')
print(y)

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 1, 1]]) 

tensor([[1, 2, 3],
        [4, 5, 6],
        [1, 1, 1]])
