In [2]:
import torch

In [3]:
#Define simple Tensor

In [20]:
x = torch.Tensor(
    [[1,2,3,4],
    [5,6,7,8],
    [1,2,3,4],
    [5,6,7,8]]
)

In [8]:
x.shape

torch.Size([2, 4])

In [12]:
#Get specialized element [1,3]
x[1,3]

tensor(8.)

In [17]:
#Get a slice of column, all items of 0 column
x[:, 0] 

tensor([1., 5.])

In [18]:
#Get a slice of row, change the indexes of slice
x[1, :]

tensor([5., 6., 7., 8.])

In [22]:
#In general: 
#x[{row}:{row}, {column}:{column}]

#Get 2 first items from 3rd column
x[0:2, 2]

tensor([3., 7.])