**Created by:**

__[Gábor Tompa](https://github.com/Galdair)__ (code and text)
<br>
__[Zoltán Ádám Milacski](https://github.com/srph25)__ (text error fixing and code optimization)



<br>

**Edited by:**

__[Zoltán Ádám Milacski](https://github.com/srph25)__

<br>

<img src="https://docs.google.com/uc?export=download&id=1WzgXsCoz8O-NeBlJTbuLPC1iIFDmgYt1" style="display:inline-block">
<hr>

# Chapter 4: Numpy II.

## Numpy Operations
The basic array manipulation methods on
* scalars
* matrices
* higher order tensors

## Reductions and Broadcasting
* Reductions are important and efficient
    * Summation, map
    * Inspired by functional programming
* Broadcasting
    * Multivariate operations on arrays with different shapes

## Shape manipulation and Sorting
* Adding new axes
* Transposing
* Sorting

## Numpy Operations

In [0]:
import numpy as np
# Numpy manipulations
scalarwise = np.arange(10)
scalarwise_plus = scalarwise + 2
scalarwise_multi = 2 ** scalarwise -1
print(scalarwise, scalarwise_plus, scalarwise_multi)

matrix = np.ones((3, 3))
print("elementwise multiplication: \n", matrix * matrix, "\nmatrix multiplication: \n", matrix.dot(matrix))

comp1 = np.arange(5)
comp2 = np.arange(5, 10)
print(comp1 == comp2) # elementwise comparison
print(np.sin(comp1)) # elementwise mathematical functions are available

[0 1 2 3 4 5 6 7 8 9] [ 2  3  4  5  6  7  8  9 10 11] [  0   1   3   7  15  31  63 127 255 511]
not matrix multiplication: 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 
matrix multiplication: 
 [[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]
[False False False False False]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025 ]
105
[3 3] [3 3] [2 4]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
(2, 3) [1 2 3 4 5 6] [[1 4]
 [2 5]
 [3 6]]
[[1]
 [2]
 [3]]
[[1 2 3]]
[2 3 1 0]
[1 2 3 4]
0 2


# Reductions and Broadcasting

In [0]:
# Reduction
summed = np.arange(15)
print(np.sum(summed))
multi_dim_sum = np.array([[1, 1], [2, 2]])
print(np.sum(multi_dim_sum), multi_dim_sum.sum(axis=0), multi_dim_sum.sum(axis=1)) # summation across different axes

# Broadcasting
broad1 = np.tile(np.arange(0, 40, 10), (3, 1)).T
broad2 = np.array([0, 1, 2])
print(broad1 + broad2) # adding up two arrays with different but broadcastable shapes works

# Shape manipulation and Sorting

In [0]:
manipulated_array= np.array([[1, 2, 3], [4, 5, 6]])
print(manipulated_array.shape, manipulated_array.ravel(), manipulated_array.T) # shape, ravel and transpose 

z = np.array([1, 2, 3])

print(z[:, np.newaxis])

print(z[np.newaxis, :])

# Sorting
a = np.array([[4, 3, 5], [1, 2, 1]])
b = np.sort(a, axis=1)

a.sort(axis=1)

a = np.array([4, 3, 1, 2])
j = np.argsort(a)
print(j)

print(a[j])

a = np.array([4, 3, 1, 2])
j_max = np.argmax(a)
j_min = np.argmin(a)
print(j_max, j_min)

(2, 3) [1 2 3 4 5 6] [[1 4]
 [2 5]
 [3 6]]
[[1]
 [2]
 [3]]
[[1 2 3]]
[2 3 1 0]
[1 2 3 4]
0 2


# References

* Basic tutorial: https://www.scipy-lectures.org/intro/numpy/operations.html

* Another tutorial: https://docs.scipy.org/doc/numpy/user/quickstart.html

* API Reference: https://docs.scipy.org/doc/numpy/reference/index.html
