**Created by:**

__[Gábor Tompa](https://github.com/Galdair)__ (code and text)
<br>
__[Zoltán Ádám Milacski](https://github.com/srph25)__ (text error fixing and code optimization)



<br>

**Edited by:**

__[Zoltán Ádám Milacski](https://github.com/srph25)__

<br>

<img src="https://docs.google.com/uc?export=download&id=1WzgXsCoz8O-NeBlJTbuLPC1iIFDmgYt1" style="display:inline-block">
<hr>

# Chapter 4: Numpy I.
## What is Numpy
* Python package for numerical computations
* Comes with many high level methods (no need to implement these again)
* The backend of these methods are actually implemented at low level (C or Fortran), hence they are order of magnitudes faster the standard Python lists
* Highly tested, facilitates scientific computation

##  Array Basics
* Creating numpy arrays from existing lists or arrays
* Multi-dimensional arrays are also available

## Creating arrays and Basic Data types
* You can create arrays, not by just copying, but by modifying individual elements
* Common matrix types are available: identity, all-ones, all-zeros
* Efficiency comes at the cost of the data type: data types are less flexible than in the case of the standard Python list.

## Indexing and Slicing
* Can be indexed just like a plain python list
* Can be sliced similarly, see code
* List comprehensions also work, but they are not encouraged, because they are slow

## Views and Fancy indexing, Boolean masks
* Views are:
    * the default way what most numpy functions return
    * NOT copies of the array (that must be forced)
    * behaves somewhat like C++ pointers or Java references
    * Important from the implementation and memory management perspective
* Fancy indexing and boolean masks are a kind of operation, more on that later
* Useful when it comes to looking for something in the array

# Array Basics

In [0]:
import numpy as np

array_one = np.array([0, 1, 2, 3])
print(array_one)

lots_of_numbers = np.arange(500)
print(lots_of_numbers)

one_dim = np.array([0, 1, 2, 3])
print(one_dim)

print(one_dim.ndim, "dimensions of an 1D array")

print(one_dim.shape, "shape of an 1D array")

print(len(one_dim), "length of the 1D array, the size of the first dimension")

two_dim = np.array([[0, 1, 2], [3, 4, 5]])

print(two_dim)

print(two_dim.ndim, "dimensions of a 2D array")

print(two_dim.shape, "shape of a 2D array")

print(len(two_dim), "length of the 2D array, the size of the first dimension")

three_dim = np.array([[[1], [2]], [[3], [4]]])
print(three_dim)

print(three_dim.ndim, "dimensions of a 3D array")

print(three_dim.shape, "shape of a 3D array")

print(len(three_dim), "length of the 3D array, the size of the first dimension")

[0 1 2 3]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 

# Creating arrays and Basic Data types

In [0]:
create_arange = np.arange(10)

print(create_arange)

create_stepwise = np.arange(1, 18, 2)

print(create_stepwise)

ones_multi_dim = np.ones((4, 5)) # (4, 5) is a tuple, the requested shape

print(ones_multi_dim)

zeros_multi_dim = np.zeros((7, 7)) # 2D 7x7 all-zeros

print(zeros_multi_dim)

eyes = np.eye(3)

print(eyes)

diagonal_matrix = np.diag(np.array([5, 6, 3]))

print(diagonal_matrix)

# Basic Data types

typed = np.array([5, 6, 88, 4])
print(typed.dtype) # int like

typed_float = np.array([5.5, 6.0, 88, 4]) # mixed arrays convert to the most general type
print(typed_float.dtype)

[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[5 0 0]
 [0 6 0]
 [0 0 3]]
int64
float64


# Indexing and Slicing

In [0]:
# Indexing and Slicing
normal_array = np.arange(30)

print(normal_array[2], normal_array[0], normal_array[29]) # getting individual elements

print(normal_array[::-1], "reversing")

two_dim_sliced = np.diag(np.arange(5))

print(two_dim_sliced[2, 2]) # row column order
start = 1
end = 20
step = 2

slicing = np.arange(50)

print(slicing[start:end:step])

2 0 29
[29 28 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6
  5  4  3  2  1  0] reversing
2
[ 1  3  5  7  9 11 13 15 17 19]


# Views and Fancy indexing, Boolean masks

In [0]:
# Array views are important for memory management (see Introduction)
original = np.arange(10)

a_view = original[::2] # A view: works like a pointer, does not consume extra memory

a_view[0] = 10

print(original,a_view)

a_copy = original[::2].copy() # Hard/Deep copy: consumes extra memory

a_copy[0] = 40

print(original, a_copy) # print to see the difference

# Fancy indexing, Boolean masks
boolean_mask_base = np.random.randint(0, 21, 15)
mask = (boolean_mask_base % 3 == 0) # an expression, which evaluates to a boolean array
only_true = boolean_mask_base[mask] # fancy indexing: getting the elements where the mask is True
print(boolean_mask_base,mask, only_true)

[10  1  2  3  4  5  6  7  8  9] [10  2  4  6  8]
[10  1  2  3  4  5  6  7  8  9] [40  2  4  6  8]
[ 2 16  7  8  9  5 10 15  8 17  2 16 17 19 14] [False False False False  True False False  True False False False False
 False False False] [ 9 15]


# References

* Scipy lectures: https://www.scipy-lectures.org/intro/numpy/array_object.html

* Tutorial: https://docs.scipy.org/doc/numpy/user/quickstart.html

* API Reference: https://docs.scipy.org/doc/numpy/reference/index.html